name: Python application

on:
push:
branches:
- main

permissions:
contents: read
packages: write

jobs:
build:
runs-on: ubuntu-latest


steps:
  - uses: actions/checkout@v4

  - name: Set up Python 3.11
    uses: actions/setup-python@v3
    with:
      python-version: "3.11"

  - name: 🔐 Login to GitHub Container Registry
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GHCR_TOKEN }}

  - name: 🏗️ Build and push Docker image
    uses: docker/build-push-action@v6
    with:
      context: .
      push: true
      tags: ghcr.io/jessicacunalata29/docker_flask:latest

  - name: 🧾 Mostrar variables básicas
    run: |
      echo "Probando conexión SSH con:"
      echo "Host: ${{ secrets.VPS_HOST }}"
      echo "Usuario: ${{ secrets.VPS_USER }}"
      echo "Puerto: ${{ secrets.VPS_SSH_PORT }}"

  - name: 🧪 Probar conexión SSH
    uses: appleboy/ssh-action@v1
    with:
      host: ${{ secrets.VPS_HOST }}
      username: ${{ secrets.VPS_USER }}
      password: ${{ secrets.VPS_PASSWORD }}
      port: ${{ secrets.VPS_SSH_PORT }}
      script: |
        echo "✅ Conexión exitosa desde GitHub Actions"
        hostname
        whoami
        uptime

  - name: 📂 Pasar stack.yml y Makefile al servidor
    uses: appleboy/scp-action@v1
    with:
      host: ${{ secrets.VPS_HOST }}
      username: ${{ secrets.VPS_USER }}
      password: ${{ secrets.VPS_PASSWORD }}
      port: ${{ secrets.VPS_SSH_PORT }}
      source: "stack.yml,Makefile"
      target: "/home/${{ secrets.VPS_USER }}/despliegue"

  - name: 🚀 Despliegue de los servicios
    uses: appleboy/ssh-action@v1
    with:
      host: ${{ secrets.VPS_HOST }}
      username: ${{ secrets.VPS_USER }}
      password: ${{ secrets.VPS_PASSWORD }}
      port: ${{ secrets.VPS_SSH_PORT }}
      script: |
        echo "✅ Desplegando servicios"

        cd ~/despliegue

        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        docker pull ghcr.io/jessicacunalata29/docker_flask:latest

        docker stack rm tecticom || true

        sleep 30

        echo "==> Desplegando stack..."
        docker stack deploy -c stack.yml --with-registry-auth tecticom

        docker ps
